name: Haber_Botu_Otomasyon
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari indir
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # <--- İŞTE BU! Python'a "Kütüphaneleri dosyada sakla" dedik.

      - name: Kutuphaneleri yukle
        run: pip install -r requirements.txt

      - name: Botu calistir
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot.py
